### ISSUE TITLE
installation issue: pre-requisite missing

### ISSUE THREAD

**Issue by nicoklinger** [torebutlin/pydvma#6]
After installing in a fresh new anaconda environment using pip, I got the following error:

`QtBindingsNotFoundError: No Qt bindings could be found`

which I believe is related to the prerequisite pyqt5 not being installed in the environment. 
Installing pyqt5 with pip in that same environment solved the issue.

**Comment by torebutlin** [comment]
Thanks for raising the issue - please can you clarify the steps you used when creating your environment and which version of python you used? I don't normally need to explicitly install pyqt as I think it gets installed with the other packages.

**Comment by nicoklinger** [comment]
Dear Dr Butlin,

The python version I am using is 3.12.7.

I created the environment from Anaconda navigator and pydvma is the 1st
library I installed (via pip).
I'll be happy to help with any other information if needed.

Best regards,
Niccolò

**Comment by torebutlin** [comment]
Thanks. It could be that you didn't install the requisites first (see installation instructions within this repo).

conda install numpy scipy jupyter matplotlib pyqtgraph
pip install pydvma

Try this and let me know if there's still an issue. It should work in python 3.12.

Best wishes
T

**Comment by nicoklinger** [comment]
I just tried it again in a new environment and it worked, I must have
missed something in the installation commands.

Apologies for the confusion and many thanks for the assistance.

Best regards,
NK
